apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-nodejs-app-4qmn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-nodejs-app-4qmn
    app.kubernetes.io/part-of: nodejs-users
  name: simple-nodejs-app-4qmn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: simple-nodejs-app-4qmn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: simple-nodejs-app-4qmn
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-lxtu-tenant/nodejs-users/simple-nodejs-app-4qmn@sha256:e56e973e0970df2c3d707e2f1c17758f7fce1f972bc854eb2bcb7795a0f04542
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
